-- Fittest Fleet: Run Runner high scores and completed plays.
-- Run this in the Supabase SQL Editor before using the leaderboard.
-- Existing high-score rows are not backfilled: they contain no play history.

create table if not exists public.run_runner_scores (
  user_id uuid primary key references auth.users (id) on delete cascade,
  display_name text not null,
  score integer not null default 0 check (score >= 0),
  updated_at timestamptz not null default now()
);

create index if not exists run_runner_scores_score_idx
  on public.run_runner_scores (score desc);

alter table public.run_runner_scores enable row level security;

drop policy if exists "Run Runner scores are publicly readable" on public.run_runner_scores;
create policy "Run Runner scores are publicly readable"
  on public.run_runner_scores
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Users can insert own Run Runner score" on public.run_runner_scores;
create policy "Users can insert own Run Runner score"
  on public.run_runner_scores
  for insert
  to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users can update own Run Runner score" on public.run_runner_scores;
create policy "Users can update own Run Runner score"
  on public.run_runner_scores
  for update
  to authenticated
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

grant usage on schema public to anon, authenticated;
grant select on table public.run_runner_scores to anon, authenticated;
grant insert, update on table public.run_runner_scores to authenticated;

create or replace function public.set_run_runner_score_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists run_runner_scores_set_updated_at on public.run_runner_scores;
create trigger run_runner_scores_set_updated_at
  before update on public.run_runner_scores
  for each row execute function public.set_run_runner_score_updated_at();

-- One immutable row per completed game. Guest plays have a null user_id.
-- This is separate from the one-row-per-user high-score table so the public
-- total includes every play while the leaderboard remains signed-in only.
create table if not exists public.run_runner_plays (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete cascade,
  points integer not null check (points >= 0),
  played_at timestamptz not null default now()
);

create index if not exists run_runner_plays_user_id_idx
  on public.run_runner_plays (user_id);
create index if not exists run_runner_plays_played_at_idx
  on public.run_runner_plays (played_at desc);

alter table public.run_runner_plays enable row level security;
alter table public.run_runner_plays alter column user_id drop not null;

drop policy if exists "Users can insert own Run Runner plays" on public.run_runner_plays;
drop policy if exists "Guests can insert Run Runner plays" on public.run_runner_plays;
create policy "Users can insert own Run Runner plays"
  on public.run_runner_plays
  for insert
  to authenticated
  with check (auth.uid() = user_id);

create policy "Guests can insert Run Runner plays"
  on public.run_runner_plays
  for insert
  to anon
  with check (user_id is null);

revoke insert on table public.run_runner_plays from anon;
grant insert (points) on table public.run_runner_plays to anon;
grant insert on table public.run_runner_plays to authenticated;

-- Keep the plays table private while allowing the board to read only its
-- aggregate. The sum includes both signed-in and null-user guest plays.
-- A missing table/function produces an RPC error in the client,
-- which intentionally leaves the UI tracker as a dash.
create or replace function public.run_runner_total_points()
returns bigint
language sql
security definer
set search_path = public
as $$
  select coalesce(sum(points), 0)::bigint
  from public.run_runner_plays;
$$;

grant execute on function public.run_runner_total_points() to anon, authenticated;
